### ISSUE TITLE
Missing prefix handling

### ISSUE THREAD

**Issue by Swiddis** [ecscstatsconsulting/morphemes#2]
The tool is incorrectly parsing words with a prefix. For example:

```py
from morphemes import *
m = Morphemes()

# Erroneous results:

# MorphoLexSegm: "{<pre<(mature)}"
assert m.parse("premature") == {
    "morpheme_count": 2,
    "status": "FOUND_IN_DATABASE",
    "tree": [{"children": [{"text": "<pre<mature", "type": "root"}], "type": "free"}],
    "word": "premature",
}

# MorphoLexSegm: "<over<{(esteem)>ate>}"
assert m.parse("overestimating") == {
    "morpheme_count": 3,
    "status": "FOUND_IN_DATABASE",
    "tree": [
        {
            "children": [
                {"text": "<over<esteem", "type": "root"},
                {"text": "ate", "type": "bound"},
            ],
            "type": "free",
        }
    ],
    "word": "overestimating",
}
```

A quick look at [the part of the code responsible for parsing](https://github.com/ecscstatsconsulting/morphemes/blob/main/morphemes/__init__.py#L30-L67) indicates that there's no checking for prefixes `<` at all.

**Comment by paul0warren** [comment]
Thanks for pointing this out!  We will get this handled shortly in a new release.

**Comment by paul0warren** [comment]
We just put out release v1.2.0 which contains a fix for this issue, unit tests were updated to include the testing of prefixes.  Thanks for taking the time to report this issue.  Should you find any problems with the fix please let us know.
